matrix:
  include:
  - language: python
    python: 3.6

    env:
      - PROTOC_PKG=protoc-3.6.0-linux-x86_64.zip
      - PROTOC_RELEASE=https://github.com/google/protobuf/releases/download/v3.6.0/$PROTOC_PKG
      - PROTOC_TARGET=${HOME}/protoc
      - PATH="${PROTOC_TARGET}/bin:${PATH}"

    before_script:
      - mkdir -p $HOME/.sbt/launchers/1.2.6/
      - curl -L -o $HOME/.sbt/launchers/1.2.6/sbt-launch.jar http://central.maven.org/maven2/org/scala-sbt/sbt-launch/1.2.6/sbt-launch-1.2.6.jar
      - rm -rf $HOME/protoc
      - wget $PROTOC_RELEASE
      - unzip $PROTOC_PKG -d $PROTOC_TARGET
      - protoc --version
      - sbt stage
      - pip install requests
      - cd cpgclientlib
    script:
      - ./runtests.sh
    deploy:
      provider: pypi
      user: "fabsx00"
      password: $PIPY_PASSWORD

  - language: scala
    jdk: oraclejdk8
    branches:
      only:
      - master

    before_install:
    - git fetch --tags
    - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE" == "push" ]]; then
         openssl aes-256-cbc -K $encrypted_663dec309dc8_key -iv $encrypted_663dec309dc8_iv -in private-key.pem.enc -out private-key.pem -d;
         gpg --import private-key.pem;
         gpg --list-keys;
      fi

    env:
      - PROTOC_PKG=protoc-3.6.0-linux-x86_64.zip
      - PROTOC_RELEASE=https://github.com/google/protobuf/releases/download/v3.6.0/$PROTOC_PKG
      - PROTOC_TARGET=${HOME}/protoc
      - PATH="${PROTOC_TARGET}/bin:${PATH}"

    install:
    - rm -rf $HOME/protoc
    - wget $PROTOC_RELEASE
    - unzip $PROTOC_PKG -d $PROTOC_TARGET
    - protoc --version
    
    script:
      - sbt test
      
    after_success:
      - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then travis_wait 60 sbt ci-release-sonatype; fi

    before_cache:
    - du -h -d 1 $HOME/.ivy2/cache
    - du -h -d 2 $HOME/.sbt/
    - find $HOME/.sbt -name "*.lock" -type f -delete
    - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
    - rm -rf $HOME/.ivy2/local

    cache:
      directories:
      - "$HOME/.sbt/1.0/dependency"
      - "$HOME/.sbt/boot/scala*"
      - "$HOME/.sbt/launchers"
      - "$HOME/.ivy2/cache"
      - "$HOME/.coursier"
